'use strict';

const load = require('../module-loader')('./json-ld/ld-*.js');

// use getters to delay module initialization and avoid circular dependencies
module.exports = {
	get action() { return load('action'); },
	get adminArea() { return load('admin-area'); },
	get aggregateRating() { return load('aggregate-rating'); },
	get application() { return load('application'); },
	get article() { return load('article'); },
	get audience() { return load('audience'); },
	get blog() { return load('blog'); },
	get blogPost() { return load('blog-post.js'); },
	get coordinates() { return load('coordinates'); },
	get creativeWork() { return load('creative-work'); },
	get dateTime() { return load('datetime'); },
	get deliveryMethod() { return load('delivery-method'); },
	get demand() { return load('demand'); },
	get duration() { return load('duration'); },
	get entryPoint() { return load('entry-point'); },
	get event() { return load('event'); },
	get image() { return load('image'); },
	get list() { return load('list'); },
	get listItem() { return load('item'); },
	get media() { return load('media'); },
	get newsArticle() { return load('news-article'); },
	get organization() { return load('organization'); },
	get ownership() { return load('ownership'); },
	get person() { return load('person'); },
	get photograph() { return load('photograph'); },
	get place() { return load('place'); },
	get post() { return load('post'); },
	get product() { return load('product'); },
	get productModel() { return load('product-model'); },
	get rating() { return load('rating'); },
	get review() { return load('review'); },
	get searchAction() { return load('search-action'); },
	get service() { return load('service'); },
	get shape() { return load('shape'); },
	get video() { return load('video'); },
	get webPage() { return load('web-page'); },
	get webSite() { return load('web-site'); },

	thing: load('thing'),
	Music: require('./music/'),

	Type: {
		action: 'Action',
		administrativeArea: 'AdministrativeArea',
		aggregateRating: 'AggregateRating',
		application: 'SoftwareApplication',
		article: 'Article',
		audience: 'Audience',
		blog: 'Blog',
		blogPost: 'BlogPosting',
		brand: 'Brand',
		breadcrumbList: 'BreadcrumbList',
		comment: 'Comment',
		coordinates: 'GeoCoordinates',
		creativeWork: 'CreativeWork',
		dateTime: 'DateTime',
		deliveryMethod: 'DeliveryMethod',
		demand: 'Demand',
		duration: 'Duration',
		entryPoint: 'EntryPoint',
		event: 'Event',
		image: 'ImageObject',
		list: 'ItemList',
		listItem: 'ListItem',
		media: 'MediaObject',
		newsArticle: 'NewsArticle',
		organization: 'Organization',
		ownership: 'OwnershipInfo',
		person: 'Person',
		photograph: 'Photograph',
		place: 'Place',
		post: 'SocialMediaPosting',
		postalAddress: 'PostalAddress',
		product: 'Product',
		productModel: 'ProductModel',
		rating: 'Rating',
		review: 'Review',
		searchAction: 'SearchAction',
		service: 'Service',
      softwareApplication: 'SoftwareApplication',
		shape: 'GeoShape',
		thing: 'Thing',
		video: 'VideoObject',
		webPage: 'WebPage',
		webSite: 'WebSite'
	}
};