'use strict';

const HashBase = require('./hash-base');
const is = require('./../is.js');
const setting = require('./../settings.js');
const log = require('./../log.js');
const hash = {};

/**
 * Hash kept in memory
 * @extends {HashBase}
 */
class Memory extends HashBase {
	constructor() {
		super();
	}

	select(key, callback) {

	}

	selectMember(key, memberKey, callback) {

	}

	selectAll(key, callback) {

	}

	/**
	 * Insert value into hash
	 * @param {String} key
	 * @param {String} value
	 * @param {Function(Object, (String|Number)} [callback] Method generated by responder()
	 */
	add(key, value, callback) {

	}

	/**
	 * Insert value into hash
	 * @param {String} key
	 * @param {String} memberKey
	 * @param {String} value
	 * @param {Function(Object, (String|Number)} [callback] Method generated by responder()
	 */
	function addMember(key, memberKey, value, callback) {

	}

	exists(key, callback) {

	}

	memberExists(key, memberKey, callback) {

	}

	keys(key, callback) {

	}

	memberKeys(key, callback) {

	}

	/**
	 * @param {String|String[]} key One or more item keys
	 * @param {function} callback
	 */
	remove(key, callback) {

	}
}

module.exports = Memory;
