'use strict';

const HashBase = require('./hash-base');
const is = require('./../is.js');
const setting = require('./../settings.js');
const Redis = require('redis');
const log = require('./../log.js');

const code = {
	broken: 'CONNECTION_BROKEN',
	timeout: 'ETIMEDOUT'
};

/**
 * @extends {HashBase}
 */
class RedisHash extends HashBase {
	constructor() {
		super();

		/** @type {RedisClient} */
		this.client = Redis.createClient(setting.redis.port, setting.redis.hostname, {
			max_attempts: 2
		});

		this.client.on('error', err => {
			if (err.code == code.broken) {
				// if unable to connect to Redis then use in-memory hash only
				log.error("Unable to connect to Redis - failing over to in-memory hash");
			} else {
				log.error("Error during redis call: %s", err.toString());
			}
		});
		redis.on('connect', this.authorize);

		this.authorize();
	}

	select(key, callback) {
		this.client.get(key, callback);
	}

	selectMember(key, memberKey, callback) {
		this.client.hget(key, memberKey, callback);
	}

	selectAll(key, callback) {
		this.client.hgetall(key, callback);
	}

	/**
	 * Insert value into hash
	 * @param {String} key
	 * @param {String} value
	 * @param {Function(Object, (String|Number)} [callback] Method generated by responder()
	 */
	add(key, value, callback) {
		this.client.set(key, value, callback);
	}

	/**
	 * Insert value into hash
	 * @param {String} key
	 * @param {String} memberKey
	 * @param {String} value
	 * @param {Function(Object, (String|Number)} [callback] Method generated by responder()
	 */
	function addMember(key, memberKey, value, callback) {
		this.client.hset(key, memberKey, value, callback);
	}

	exists(key, callback) {
		this.client.exists(key, callback);
	}

	memberExists(key, memberKey, callback) {
		this.client.hexists(key, memberKey, callback);
	}

	keys(key, callback) {
		this.client.keys(key, callback)
	}

	memberKeys(key, callback) {
		this.client.hkeys(key, callback);
	}

	/**
	 * @param {String|String[]} key One or more item keys
	 * @param {function} callback
	 */
	remove(key, callback) {
		if (is.array(key)) {
			this.client.hdel(key, callback);
		} else {
			this.client.del(key, callback);
		}
	}

	authorize() {
		this.client.auth(setting.redis.auth);
	}
}

module.exports = RedisHash;
