"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var post_1 = require("./post");
exports.post = post_1.post;
var category_1 = require("./category");
exports.category = category_1.category;
var photo_1 = require("./photo");
exports.photo = photo_1.photo;
var static_1 = require("./static");
exports.staticPage = static_1.staticPage;
var menu_1 = require("./menu");
exports.menu = menu_1.menu;
var auth_1 = require("./auth");
exports.auth = auth_1.auth;
var map_1 = require("./map");
exports.map = map_1.map;
var rss_1 = require("./rss");
exports.postFeed = rss_1.postFeed;
