'use strict';

const TI = require('../../');
const CacheProvider = TI.Provider.Cache.Base;

/**
 * @extends {CacheBase}
 */
class SqlCache extends CacheProvider {
	select(key, callback) {

	}

	selectMember(key, memberKey, callback) {

	}

	selectAll(key, callback) {

	}

	/**
	 * Insert value into hash
	 * @param {String} key
	 * @param {String} value
	 * @param {Function(Object, (String|Number)} [callback] Method generated by responder()
	 */
	add(key, value, callback) {

	}

	/**
	 * Insert value into hash
	 * @param {String} key
	 * @param {String} memberKey
	 * @param {String} value
	 * @param {Function(Object, (String|Number)} [callback] Method generated by responder()
	 */
	addMember(key, memberKey, value, callback) {

	}

	addAll(key, hash, callback) {

	}

	exists(key, callback) {

	}

	memberExists(key, memberKey, callback) {

	}

	keys(key, callback) {

	}

	memberKeys(key, callback) {

	}

	/**
	 * @param {String|String[]} key One or more item keys
	 * @param {function} callback
	 */
	remove(key, callback) {

	}

	removeMember(key, memberKey, callback) {

	}
}

module.exports = SqlCache;
